### PR TITLE
Added All Other Female Hostel ID to Halls

### PR DESCRIPTION
**Pull request by timzprof**

### CODE REVIEW

**Comment by timzprof** [comment]
Seems like the data folders are causing conflict

**Comment by tiemma** [comment]
Yes, they are copies of each other that just allow you run more than one.

If one folder is in use, the other ones can be used so a restart would fix that cause the number is picked randomly

**Comment by timzprof** [comment]
How to resolve the conflict tho?

**Comment by tiemma** [comment]
> 
> 
> How to resolve the conflict tho?

It'd have to be fixed manually on a PC.

Clone, merge then push again

**Comment by tiemma** [comment]
git checkout female-dev
git merge --no-ff timzprof-female-dev
git push origin female-dev

Instructions here

**Pull request merged**
